const articulo1= new Articulo("1144","Let It Be Special Edition","Let It Be Special Edition (Standard): 12 tracks 1CD in digipak (new stereo mix of original album)",35.00,0,"Media","Black","Imagenes/E-Commerce/LetitbeCD.jpg",0)
const articulo2= new Articulo("2244","Let It Be Embroidered Blue","Show your love for The Beatles with this crewneck sweatshirt!",65.00,0,"Vestimenta","Azul","Imagenes/E-Commerce/LetitBeCanguro.jfif",0)
const articulo3= new Articulo("3344","Let It Be Photo Red","Show your love for The Beatles with this crewneck sweatshirt!",50.00,0,"Vestimenta","Red","Imagenes/E-Commerce/LetItbeCanguroRojojfif.jfif",0)
const articulo4= new Articulo("4444","Let It Be Igloo Cooler","You'll LOVE keeping your favorite foods and drinks fresh with your own special-edition Beatles and Yellow Submarine-inspired Igloo Coolers. Each design is featured on Igloo's 7qt Little Playmate Silhouette.",40.00,0,"Home","Black and White","Imagenes/E-Commerce/Launchera.jfif",0)
const articulo5=new Articulo("5544","Pantomime:Christmas Tote","This 12oz, 100% cotton canvas tote features art from the 1964 record Pantomime: Everywhere It’s Christmas.",20.00,0,"Fhater´s Day","Yellow,Blue","Imagenes/E-Commerce/bolso.jpg",0)
const articulo6=new Articulo("6644","Abbey Road Ukulele","Totally unique, with iconic graphics from 1965 to 1970, the Beatles nylon strung ukuleles make an ideal beginner's instrument, or are perfect for avid fans and collectors. Featuring a wood body for excellent sound projection and tone, smooth adjustable machine heads for accurate tuning and strap button, this bright and colorful ukulele puts the fun back into learning to play the uke.",60.00,0,"Accesories","Light Blue","Imagenes/E-Commerce/UkuleleAbbey.jfif",0)
const articulo7=new Articulo("7744","Port Hole Beanie","Warm, cozy, and stylish navy blue beanie with embroidered patches of the guys in their Yellow Submarine.",40.00,0,"Accesories","Black,Red,White","Imagenes/E-Commerce/gorroYsub.jfif",0)
const articulo8=new Articulo("8844","I Love The Beatles Pin","",200,0,"Imagenes/E-Commerce/PIN.jfif",0)
const articulo9= new Articulo("9944","Launchera - The Beatles","",8250,0,"Imagenes/E-Commerce/Launchera.jfif",0)
const articulo10=new Articulo("1155","Hornby London Bus","",1750,0,"Imagenes/E-Commerce/BusBeatles.jpg",0)
const articulo11=new Articulo("2255","Let It Be Cookie Jar","Show your love for The Beatles with this iconic cookie jar!",59.00,0,"Home","Black","Imagenes/E-Commerce/letitbecockjair.jfif",0)
const articulo12=new Articulo("3355","Embroidered Olive Beanie","",1360,0,"Imagenes/E-Commerce/Gorralet.jfif",0)
const articulo13=new Articulo("4455","Let It Be Color Faces Youth Raglan","",200,0,"Imagenes/E-Commerce/Y3CTBE219.jfif",0)


const usuario1=new Usuario("Luciano","Cedrez","lcedrez","Luciano1234")
const usuario2=new Usuario("Juan","Perez","jperez","Juan1234567")
const usuario3=new Usuario("Carlos","Gonzalez","cgonzalez","Carlos2487")
const usuario4=new Usuario("Luis","Martinez","lmartinez","Luis4545")

