const articulo1= new Articulo("1144","Let It Be Special Edition",2500,0,"Imagenes/E-Commerce/LetitbeCD.jpg")
const articulo2= new Articulo("2244","Let It Be Embroidered Blue",4200,0,"Imagenes/E-Commerce/LetitBeCanguro.jfif")
const articulo3= new Articulo("3344","Let It Be Photo Red",5200,0,"Imagenes/E-Commerce/LetItbeCanguroRojojfif.jfif")
const articulo4= new Articulo("4444","Launchera - The Beatles",8250,0,"Imagenes/E-Commerce/Launchera.jfif")
const articulo5=new Articulo("5544","Beatles Playing Cards ",1250,0,"Imagenes/E-Commerce/BeatlesCard.jpg")
const articulo6=new Articulo("6644","Abbey Road Ukulele",17500,0,"Imagenes/E-Commerce/UkuleleAbbey.jfif")
const articulo7=new Articulo("7744","Port Hole Beanie",1500,0,"Imagenes/E-Commerce/gorroYsub.jfif")
const articulo8=new Articulo("8844","I Love The Beatles Pin",200,0,"Imagenes/E-Commerce/PIN.jfif")
const articulo9= new Articulo("9944","Launchera - The Beatles",8250,0,"Imagenes/E-Commerce/Launchera.jfif")
const articulo10=new Articulo("1155","Hornby London Bus",1750,0,"Imagenes/E-Commerce/BusBeatles.jpg")
const articulo11=new Articulo("2255","Let It Be Cookie Jar",1750,0,"Imagenes/E-Commerce/letitbecockjair.jfif")
const articulo12=new Articulo("3355","Embroidered Olive Beanie",1360,0,"Imagenes/E-Commerce/Gorralet.jfif")
const articulo13=new Articulo("4455","Let It Be Color Faces Youth Raglan",200,0,"Imagenes/E-Commerce/Y3CTBE219.jfif")


const usuario1=new Usuario("Luciano","Cedrez","lcedrez","Luciano1234")
const usuario2=new Usuario("Juan","Perez","jperez","Juan1234567")
const usuario3=new Usuario("Carlos","Gonzalez","cgonzalez","Carlos2487")
const usuario4=new Usuario("Luis","Martinez","lmartinez","Luis4545")
